version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=user
      - MARIADB_USER=user
      - MARIADB_PASSWORD=user
    ports:
      - "3306:3306"
    command:
      - --max-allowed-packet=1073741824 #1 GB

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=1G
      - MEMORY_LIMIT=2G
     # - PMA_USER=root
     # - PMA_PASSWORD=root
    depends_on:
      - mariadb